#!/usr/bin/env bash

set -eo pipefail

serieslist() {

  find . \
    -maxdepth 1 \
    -name '*.series' \
    -type f \
    -exec basename {} \; \
    | while read -r file; do
      echo "${file%%.series}"
    done

}

main() {

  set +e
  serieslist \
    | fzf \
      --delimiter=.series \
      --with-nth=1 \
      --preview-window=down \
      --preview './seriesinfo {}'

}

main "$@"
