#!/usr/bin/env bash

# Removes all <a name="..."></a> lines except if it's specifically "foonotes"

declare FILE="${1:?Specify file path}"

grep -P -n '^<a name="(?!footnotes)' "$FILE" \
	| cut -f1 -d"<" \
	| sed 's/:/d/' \
	| paste -sd';' \
	| sed -i -f - "$FILE"
