#!/usr/bin/env bash

set -eo pipefail

declare seriesfile="${1:?Specify series name}.series"

while read -r file; do
  yq --front-matter=extract \
    '"\(.date) \(.title)"' \
    "$file"
done < "$seriesfile"
