#!/usr/bin/env bash

# Remove old post files
rm -f posts/*

# Parse the JSON output from the Khoros API and emit post snippets separated by `~~~`
# Then split that output into separate files
./blogposts.jq sapcommunityposts.json | csplit -f 'posts/post' -z --suppress-matched - /~~~/ '{*}'

# Rename each file with the first line of the file content which is:
# yyyy-mm-dd-post-title-slug
cd posts/
for f in post*; do
  mv $f $(head -1 $f)
done

