#!/usr/bin/env bash

set -o errexit

declare post="${1:?Specify post ID}"
declare postid="${post##*/}"
declare postdir="./posts/save/${postid}"

declare title="$(sed "2q;d" $post)"
declare date="$(sed "4q;d" $post)"
declare url="$(sed "5q;d" $post)"

mkdir -p "$postdir/src/posts" "$postdir/src/images"
tree $postdir



cat <<EOF > "${postdir}/src/posts/${postid}.md"
---
layout: post
title: "${title}"
date: ${date}
tags:
  - sapcommunity
---

---

[Originally published on SAP Community](${url})
EOF
