#!/usr/bin/env bash

declare postdir="../posts"

sed -i -E 's/\[\!.+\]\(\/content\/images(.+)\)/![image]({{ "\/img\1" | url }})/' "$postdir"/*.markdown
sed -i -E '/^date: /d; s/\(\/content\/images(\/.+?)\)/( {{ "\/img\1" | url }})/g' "$postdir"/*.markdown
